from data_cleaning.uci_handler import UCI_Handler

if __name__ == "__main__":
    uh = UCI_Handler()

    # ------- Training --------

    # Where to find csv file generated by `uh.saveUCIFilesAsCSV` function.
    data_folder = r"/Users/matin/Dropbox/Work-Research/Current Directory/Shape Features/Data/UCI dataset/UCI HAR Dataset/train/"
    # csv filename
    data_filename = r"train_total_acc_data.csv"
    # Where to save the new 10Hz data files (separated for each subject)
    out_folder = r"/Users/matin/Dropbox/Work-Research/Current Directory/Shape Features/Data/UCI dataset/UCI HAR Dataset/downsampled/Total/Training/"

    uh.downsampleAndSeparateSubjectData(data_folder, data_filename, out_folder)


    # ------- Test --------

    # Where to find csv file generated by `uh.saveUCIFilesAsCSV` function.
    data_folder = r"/Users/matin/Dropbox/Work-Research/Current Directory/Shape Features/Data/UCI dataset/UCI HAR Dataset/test/"
    # csv filename
    data_filename = r"test_total_acc_data.csv"
    # Where to save the new 10Hz data files (separated for each subject)
    out_folder = r"/Users/matin/Dropbox/Work-Research/Current Directory/Shape Features/Data/UCI dataset/UCI HAR Dataset/downsampled/Total/Test/"

    uh.downsampleAndSeparateSubjectData(data_folder, data_filename, out_folder)